query GetUserById($userId: String!) {
    getUser(id: $userId) {
        id
        firstName
        lastName
        bio
        dateOfBirth

        bookReviews {
            id
            body
            rating

            book {
                id
                title
            }
        }
    }
}

query GetMySentFriendInvites($userId: String!) {
    sentFriendInvitations(userId: $userId) {
        id        
    }
}

query GetMyReceivedFriendInvites($userId: String!) {
    pendingFriendInvitations(userId: $userId) {
        id
    }
}

mutation SendFriendInvite($userId: String!) {
    inviteFriend(friendId: $userId)
}