query GetAuthorsList ($pageLimit: Int!, $startOffset: Int!) {

  listAuthors (connectionBuilder: { edgesPerPage: $pageLimit, startOffset: $startOffset }) {
    edges {
        node {
            id
            firstName
            lastName
            dateOfBirth
            dateOfDeath
            hometown
            bio
          }
    }
  }
}