query GetAuthorsList ($first: Int!, $page: Int!) {

  listAuthors ( first: $first, page: $page) {
    edges {
        node {
            id
            firstName
            lastName
            dateOfBirth
            dateOfDeath
            hometown
            bio
          }
    }
  }
}