query GetAuthorsList {
    listAuthors {
        pageInfo {
            totalEdges
            hasNextPage
            hasPreviousPage
        }

        edges {
            node {
                id
                firstName
                lastName
                dateOfBirth
                dateOfDeath
            }
        }
    }
}