query GetBooksList($titleSearchTerm: String) {
    listBooks(filter: { title: $titleSearchTerm }) {
        pageInfo {
            totalEdges
            hasNextPage
            hasPreviousPage
        }

        edges {
            node {
                id
                coverImage
                title
                publicationDate

                authors {
                    firstName
                    lastName
                }
            }
        }
    }
}
