query GetBooksList {
    listBooks {
        pageInfo {
            totalEdges
            hasNextPage
            hasPreviousPage
        }

        edges {
            node {
                id
                coverImage
                title
                publicationDate

                authors {
                    firstName
                    lastName
                }
            }
        }
    }
}
