query GetBooksList($first: Int!, $page: Int!) {

    listBooks(first: $first, page: $page ) {
        pageInfo {
            totalEdges
            hasNextPage
            hasPreviousPage
        }
        edges {
            node {
                id
                coverImage
                title
                authors {
                    firstName
                    lastName
                 }
                publicationDate
            }
        }
    }
}
