query GetBookById($bookId: String!) {
    getBook(id: $bookId) {
        id
        title
        coverImage
        authors {
            id
            firstName
            lastName
        }
        publicationDate
        synopsis

        bookReviews {
            id
            body
            rating

            user {
                id
                firstName
                lastName
            }
        }
    }
}

query GenerateReview($reviewer: Int!, $bookId: String!) {
    generateReview(reviewer: $reviewer, bookId: $bookId)
}

mutation CreateBookReview($input: CreateBookReviewInput!) {
    createBookReview(input: $input) {
        id
        body
        rating
    }
}
