query GetUserFriends($userId: String!) {
  getUser(id: $userId) {
    friends{
      id
      firstName
      lastName
    }
  }
}

mutation AcceptFriendInvite($userId: String!) {
    acceptFriendInvitation(friendId: $userId)
}